module.exports = Object.freeze({
  BASE_URL: 'http://test-agency.zadanetwork.com',
  WALLET_SECRET: 'wallet_secret',
  WALLET_NAME: 'wallet_name',
  CERT_REQ: 'connection_credential',
  CONNEC_REQ: 'connection_request',
  CRED_REQ: 'credential_offer',
  PROOF_REQ: 'connection_proof',
  CONNECTIONS: 'connections',
  USER_TOKEN: 'userToken',
  USER_AUTH: 'userAuth',
  DEVICE_TOKEN: 'deviceToken',
  USER_ID: 'userId',
  CREDENTIALS: 'credentials',
  API_SECRET: '',
});
