module.exports = Object.freeze({
  //BASE_URL: 'http://8130-111-119-187-42.ngrok.io',
  BASE_URL: 'http://test-agency.zadanetwork.com',
  //BASE_URL: 'https://agency.zadanetwork.com',
  ZADA_AUTH_URL: 'https://auth-test.zadanetwork.com',
  //ZADA_AUTH_URL: 'http://0876-182-191-89-195.ngrok.io',
  ZADA_AUTH_SECRET: 'doingtestinginzadaauth',
  ZIGNSEC_TEST_URL: 'https://test.zignsec.com/v3',
  ZIGNSEC_WEBHOOK: 'http://ce63-206-84-130-27.ngrok.io/api/kycs_webhook',
  ZIGNSEC_TEST_AUTH: 'fd0b1bac-5707-4f32-8132-e8c9168941ea',
  ZADA_S3_BASE_URL:
    'https://zada-wallet-cred-bg.s3.ap-southeast-1.amazonaws.com',
  ZADA_AUTH: 'zada_auth',
  WALLET_SECRET: 'wallet_secret',
  WALLET_NAME: 'wallet_name',
  CERT_REQ: 'connection_credential',
  CONN_REQ: 'connection_request',
  CRED_OFFER: 'credential_offer',
  VER_REQ: 'verification_request',
  CONNLESS_VER_REQ: 'connectionless_verification',
  PROOF_REQ: 'connection_proof',
  CONNECTIONS: 'connections',
  USER_TOKEN: 'userToken',
  USER_AUTH: 'userAuth',
  DEVICE_TOKEN: 'deviceToken',
  USER_ID: 'userId',
  CREDENTIALS: 'credentials',
  API_SECRET: '',
  BIOMETRIC_ENABLED: 'biometric_enabled',
  NOTIFICATION_ENABLED: 'notification_enabled',
  COUNTDOWN_TIME: 'countdown_time',
  USER_PROFILE: 'user_profile',
  REGISTRATION_DATA: 'register_data',
  LOGIN_DATA: 'login_data',
  PIN_CODE: 'pin_code',
  ZADA_AUTH_TEST: 'ZADA Auth Test',
  ZADA_AUTH_CONNECTION_ID: 'f743ac9a-9758-495d-bfbc-74421ae6d1e9',
  QR_URL: 'https://api.qrserver.com/v1/create-qr-code/?size=512x512&data=',
  VER_KEY: 'verkey',
  ZIGN_SEC_TIME: 'zignsectime',
  KYC_STATUS: 'kyc_status',
  APP_VERSION: 'app_version',
  STRONG: 'Strong',
  MEDIUM: 'Medium',
  WEAK: 'Weak',
});
